const starterActivities=[{name:'Chemistry',caption:'Bonding · Exam in 12 days',score:54,color:'#88a987',icon:'⚗',bg:'#eff5ed'},{name:'Mathematics',caption:'Algebra · Building momentum',score:76,color:'#a99ac2',icon:'∑',bg:'#f3f0f7'},{name:'Biology',caption:'Cell biology · On track',score:82,color:'#d2a276',icon:'❋',bg:'#fbf3eb'},{name:'Spanish',caption:'Vocabulary · Ready to review',score:61,color:'#7da9ab',icon:'あ',bg:'#edf5f5'}];
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let activities=read('coachai.activities',starterActivities),sessions=read('coachai.sessions',8),mastery=read('coachai.mastery',68);
let currentUser=null,persistTimer=null,currentToken=sessionStorage.getItem('coachai.session')||'';
const $=s=>document.querySelector(s),activityLinks=$('#activityLinks'),focusList=$('#focusList');
function persistLearnerState(){if(!currentUser)return;clearTimeout(persistTimer);persistTimer=setTimeout(()=>api('/api/state',{state:{activities,sessions,mastery}}).catch(()=>{}),250)}
function render(){activityLinks.innerHTML=activities.map(a=>`<div class="activity-link"><i class="activity-dot" style="background:${a.color}"></i>${escapeHTML(a.name)}</div>`).join('');focusList.innerHTML=activities.slice(0,3).map(a=>`<div class="focus-row"><div class="focus-icon" style="background:${a.bg};color:${a.color}">${a.icon}</div><div><div class="focus-name">${escapeHTML(a.name)}</div><div class="focus-caption">${escapeHTML(a.caption)}</div><div class="focus-bar"><i style="width:${a.score}%;background:${a.color}"></i></div></div><div class="focus-score">${a.score}%</div></div>`).join('');const sessionStat=document.querySelector('.stat-card:nth-child(3) .stat-value');if(sessionStat)sessionStat.innerHTML=`${sessions}<span class="subvalue"> / 10</span>`;const badge=document.querySelector('.nav-item em');if(badge)badge.textContent=activities.length;localStorage.setItem('coachai.activities',JSON.stringify(activities));localStorage.setItem('coachai.sessions',sessions);localStorage.setItem('coachai.mastery',mastery);persistLearnerState()}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
render();
const sessionDialog=$('#sessionDialog'),activityDialog=$('#activityDialog');$('#startSession').onclick=()=>sessionDialog.showModal();$('#nextArrow').onclick=()=>sessionDialog.showModal();$('#closeDialog').onclick=()=>sessionDialog.close();$('#addActivity').onclick=()=>activityDialog.showModal();$('#viewActivities').onclick=()=>document.querySelector('.focus-panel').scrollIntoView({behavior:'smooth',block:'center'});
let answered=0;document.querySelectorAll('.answer').forEach((button,index)=>button.onclick=()=>{if(answered)return;answered=1;button.classList.add(index===1?'correct':'incorrect');if(index!==1)document.querySelectorAll('.answer')[1].classList.add('correct');$('.session-step').querySelector('.session-progress span').textContent='QUESTION 1 OF 3 · ANSWER RECORDED';$('.hint-row').innerHTML=index===1?'<span>Exactly — shared electrons make a covalent bond.</span>':'<span>Atoms share electrons in a covalent bond. We’ll revisit this next time.</span>';setTimeout(()=>{$('.session-step').hidden=true;$('.session-result').hidden=false},850)});
$('#hintBtn').onclick=()=>$('#hintText').textContent='Think about whether the atoms share or transfer electrons.';$('#finishSession').onclick=()=>{sessionDialog.close();sessions=Math.min(10,sessions+1);mastery=Math.min(100,mastery+1);activities=activities.map(a=>a.name==='Chemistry'?{...a,score:Math.min(100,a.score+4),caption:'Bonding · Just practiced'}:a);answered=0;$('.session-step').hidden=false;$('.session-result').hidden=true;document.querySelectorAll('.answer').forEach(b=>b.classList.remove('correct','incorrect'));render()};
$('#activityForm').onsubmit=e=>{e.preventDefault();const data=new FormData(e.currentTarget),name=String(data.get('name')).trim();if(!name)return;const palette=[['#88a987','#eff5ed','✳'],['#a99ac2','#f3f0f7','◈'],['#d2a276','#fbf3eb','✦'],['#7da9ab','#edf5f5','◎']][activities.length%4];activities.push({name,caption:String(data.get('goal')||'A new goal · Ready to begin'),score:0,color:palette[0],bg:palette[1],icon:palette[2]});render();e.currentTarget.reset();activityDialog.close()};

// Coursework and due date calendar
const dateKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const offsetDate=n=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return dateKey(d)};
let assignments=read('coachai.assignments',[
 {id:'seed-chem',title:'Finish bonding practice set',subject:'Chemistry',due:offsetDate(1),priority:'high',duration:'30 min',done:false},
 {id:'seed-math',title:'Algebra problem set',subject:'Mathematics',due:offsetDate(3),priority:'medium',duration:'1 hour',done:false},
 {id:'seed-bio',title:'Revise cell structure',subject:'Biology',due:offsetDate(5),priority:'low',duration:'30 min',done:false}
]);
let selectedDay=dateKey(new Date());
function prettyDate(key){return new Intl.DateTimeFormat('en',{weekday:'short',month:'short',day:'numeric'}).format(new Date(`${key}T12:00:00`))}
function daysAway(key){const d=new Date();d.setHours(12,0,0,0);return Math.round((new Date(`${key}T12:00:00`)-d)/86400000)}
function renderAssignments(){const mode=$('#taskFilter').value,shown=assignments.filter(a=>mode==='all'||(mode==='done'?a.done:!a.done)).sort((a,b)=>Number(a.done)-Number(b.done)||a.due.localeCompare(b.due));$('#assignmentList').innerHTML=shown.map(a=>{const n=daysAway(a.due),due=a.done?'Completed':n<0?`${-n}d overdue`:n===0?'Due today':n===1?'Due tomorrow':prettyDate(a.due);return `<div class="assignment-row ${a.done?'is-done':''}"><input class="task-check" type="checkbox" data-task="${escapeHTML(a.id)}" ${a.done?'checked':''} aria-label="Mark task complete"><div><div class="task-title">${escapeHTML(a.title)}</div><div class="task-meta"><span class="task-subject">${escapeHTML(a.subject||'Personal')}</span><span>·</span><span>${escapeHTML(a.duration||'')}</span><span class="priority-pill ${escapeHTML(a.priority)}">${escapeHTML(a.priority)}</span></div></div><div class="task-due ${!a.done&&n<=1?'soon':''}">${escapeHTML(due)}</div></div>`}).join('');const open=assignments.filter(a=>!a.done).length;$('#assignmentSummary').textContent=open?`${open} task${open===1?'':'s'} to go · sorted by due date`:'All caught up · add another task when you need to';$('#emptyAssignments').hidden=shown.length>0;$('#assignmentList').hidden=shown.length===0;$('#assignmentList').querySelectorAll('.task-check').forEach(c=>c.onchange=()=>{const a=assignments.find(x=>x.id===c.dataset.task);if(a)a.done=c.checked;saveAssignments()})}
function renderWeek(){const today=new Date();today.setHours(12,0,0,0);const monday=new Date(today);monday.setDate(today.getDate()-((today.getDay()+6)%7));$('#calendarWeek').innerHTML=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);const k=dateKey(d),has=assignments.some(a=>a.due===k&&!a.done);return `<button class="day-cell ${k===dateKey(today)?'today':''} ${k===selectedDay?'selected':''} ${has?'has-due':''}" data-day="${k}"><span>${new Intl.DateTimeFormat('en',{weekday:'short'}).format(d).toUpperCase()}</span><b>${d.getDate()}</b></button>`}).join('');$('#calendarWeek').querySelectorAll('.day-cell').forEach(b=>b.onclick=()=>{selectedDay=b.dataset.day;renderWeek()});const events=assignments.filter(a=>a.due===selectedDay);$('#calendarEvents').innerHTML=events.length?events.map(a=>`<div class="calendar-event"><i class="event-mark" style="background:${a.priority==='high'?'#cf9471':'#8baa8a'}"></i><span><b>${escapeHTML(a.title)}</b><small>${escapeHTML(a.subject||'Personal')} · ${a.done?'Completed':'Due '+(daysAway(a.due)===0?'today':daysAway(a.due)===1?'tomorrow':prettyDate(a.due))}</small></span><time>${escapeHTML(a.duration||'')}</time></div>`).join(''):`<div class="calendar-empty">Nothing due ${selectedDay===dateKey(today)?'today':'on '+prettyDate(selectedDay)}. A little breathing room.</div>`}
function saveAssignments(){localStorage.setItem('coachai.assignments',JSON.stringify(assignments));renderAssignments();renderWeek();if(currentUser)syncAssignments()}
function renderPlanner(){renderAssignments();renderWeek()}
renderPlanner();
$('#taskFilter').onchange=renderAssignments;$('#addAssignment').onclick=()=>{const f=$('#assignmentForm');f.elements.due.min=dateKey(new Date());f.elements.due.value=offsetDate(1);$('#assignmentDialog').showModal()};$('#closeAssignment').onclick=()=>$('#assignmentDialog').close();$('#calendarToday').onclick=()=>{selectedDay=dateKey(new Date());renderWeek()};
$('#assignmentForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget);assignments.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),title:String(d.get('title')).trim(),subject:String(d.get('subject')).trim(),due:String(d.get('due')),priority:String(d.get('priority')),duration:String(d.get('duration')),done:false});selectedDay=String(d.get('due'));saveAssignments();e.currentTarget.reset();$('#assignmentDialog').close()};

const API_BASE=(window.COACH_API_BASE||'').replace(/\/$/,'');
async function api(path,data){const options={method:data?'POST':'GET',headers:{}};if(data){options.headers['Content-Type']='application/json';options.body=JSON.stringify(data)}if(currentToken)options.headers.Authorization=`Bearer ${currentToken}`;const response=await fetch(`${API_BASE}${path}`,options);const result=await response.json();if(!response.ok)throw new Error(result.error||'Something went wrong.');return result}
async function syncAssignments(){try{for(const task of assignments)await api('/api/assignments',task)}catch(error){console.error('Could not sync coursework:',error)}}
function showAuth(message=''){document.body.classList.remove('app-loading');$('#authGate').hidden=false;$('#authError').textContent=message}
function showProfile(email){const local=email.split('@')[0],name=local.replace(/[._-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase());$('#profileInitial').textContent=(name[0]||'S').toUpperCase();$('#profileName').textContent=name||'Student';$('#profileEmail').textContent=email;$('#accountButton').textContent=(name[0]||'S').toUpperCase();$('#accountButton').title=email}
function hideAuth(email){currentUser=true;document.body.classList.remove('app-loading');$('#authGate').hidden=true;showProfile(email)}
function updateAuthMode(mode){document.querySelectorAll('.auth-tab').forEach(t=>t.classList.toggle('active',t.dataset.mode===mode));const isLogin=mode==='login';$('#authForm').dataset.mode=mode;$('#authForm').elements.password.autocomplete=isLogin?'current-password':'new-password';$('#authForm').elements.password.minLength=isLogin?1:10;$('.auth-submit').innerHTML=isLogin?'Sign in <span>→</span>':'Create your account <span>→</span>';$('#authError').textContent=''}
document.querySelectorAll('.auth-tab').forEach(t=>t.onclick=()=>updateAuthMode(t.dataset.mode));
$('#authForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,mode=form.dataset.mode||'signup',button=form.querySelector('.auth-submit');button.disabled=true;button.textContent=mode==='signup'?'Creating your account…':'Signing in…';$('#authError').textContent='';try{const d=new FormData(form),email=String(d.get('email')).trim().toLowerCase(),session=await api(`/api/${mode}`,{email,password:d.get('password')});currentToken=session.token;sessionStorage.setItem('coachai.session',currentToken);const profile=await api('/api/me');activities=profile.state.activities||starterActivities;sessions=profile.state.sessions??8;mastery=profile.state.mastery??68;assignments=(profile.assignments||[]).map(a=>({...a,done:Boolean(a.done)}));render();renderPlanner();hideAuth(email)}catch(err){$('#authError').textContent=err.message}finally{button.disabled=false;button.innerHTML=mode==='signup'?'Create your account <span>→</span>':'Sign in <span>→</span>'}};
async function boot(){document.body.classList.add('app-loading');try{const profile=await api('/api/me');if(profile.user){currentUser=true;activities=profile.state.activities||starterActivities;sessions=profile.state.sessions??8;mastery=profile.state.mastery??68;assignments=(profile.assignments||[]).map(a=>({...a,done:Boolean(a.done)}));render();renderPlanner();showProfile(profile.user.email);document.body.classList.remove('app-loading')}else{updateAuthMode('signup');showAuth()}}catch{showAuth(API_BASE?'The Coach AI service is starting or temporarily unavailable. Try again shortly.':'Start Coach AI with the included Python server, then refresh this page.')}}
boot();
$('#accountButton').onclick=async()=>{if(!confirm(`Sign out of ${$('#accountButton').title||'Coach AI'}?`))return;try{await api('/api/logout',{})}finally{currentUser=null;currentToken='';sessionStorage.removeItem('coachai.session');location.reload()}};

$('#openCoach').onclick=()=>$('#coachDialog').showModal();$('#closeCoach').onclick=()=>$('#coachDialog').close();
function addChatBubble(text,kind){const bubble=document.createElement('div');bubble.className=`chat-bubble ${kind==='user'?'user-bubble':'coach-bubble'}`;bubble.textContent=text;$('#chatMessages').append(bubble);$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight;return bubble}
$('#chatForm').onsubmit=async e=>{e.preventDefault();const form=e.currentTarget,field=form.elements.message,message=field.value.trim();if(!message)return;addChatBubble(message,'user');field.value='';const pending=addChatBubble('Thinking through that with you…','coach');form.querySelector('button').disabled=true;try{const history=[...$('#chatMessages').querySelectorAll('.chat-bubble')].slice(-7).map(n=>n.textContent).join('\n');const result=await api('/api/coach',{message,context:`Recent chat:\n${history}\n\nUpcoming coursework:\n${assignments.filter(a=>!a.done).slice(0,5).map(a=>`${a.subject}: ${a.title} (${a.due})`).join('\n')||'No upcoming tasks saved.'}`});pending.textContent=result.answer}catch(err){pending.textContent=err.message}finally{form.querySelector('button').disabled=false;field.focus()}};
