const starterActivities=[];
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let activities=read('coachai.activities',starterActivities),sessions=read('coachai.sessions',0),mastery=read('coachai.mastery',0);
let studyMinutes=read('coachai.minutes',0), chatHistory=read('coachai.chat',[]);
const $=s=>document.querySelector(s),activityLinks=$('#activityLinks'),focusList=$('#focusList');
function persistLearnerState(){localStorage.setItem('coachai.activities',JSON.stringify(activities));localStorage.setItem('coachai.sessions',sessions);localStorage.setItem('coachai.mastery',mastery);localStorage.setItem('coachai.minutes',studyMinutes)}
function render(){activityLinks.innerHTML=activities.map(a=>`<div class="activity-link"><i class="activity-dot" style="background:${a.color}"></i>${escapeHTML(a.name)}</div>`).join('');focusList.innerHTML=activities.length?activities.slice(0,3).map(a=>`<div class="focus-row"><div class="focus-icon" style="background:${a.bg};color:${a.color}">${a.icon}</div><div><div class="focus-name">${escapeHTML(a.name)}</div><div class="focus-caption">${escapeHTML(a.caption)}</div><div class="focus-bar"><i style="width:${a.score}%;background:${a.color}"></i></div></div><div class="focus-score">${a.score}%</div></div>`).join(''):'<div class="calendar-empty">Add a subject or activity to track your learning here.</div>';const sessionStat=document.querySelector('.stat-card:nth-child(3) .stat-value');if(sessionStat)sessionStat.innerHTML=`${sessions}<span class="subvalue"> total</span>`;const badge=document.querySelector('.nav-item em');if(badge)badge.textContent=activities.length;const values=document.querySelectorAll('.stat-card .stat-value');if(values[0])values[0].innerHTML=`${assignments.filter(a=>a.done).length}<span> / ${assignments.length} tasks</span>`;if(values[1])values[1].innerHTML=`${activities.length}<span class="percent"> subjects</span>`;const cards=document.querySelectorAll('.stat-card');cards[0].querySelector('.stat-foot').textContent=assignments.length?`${assignments.filter(a=>!a.done).length} remaining · ${assignments.filter(a=>a.done).length} completed`:'Add coursework to see progress';cards[1].querySelector('.stat-foot').textContent=activities.length?'Your subjects and goals':'Add a subject to start tracking';cards[2].querySelector('.stat-foot').textContent='Practice checks completed';$('.chart-area').innerHTML=`<p class="calendar-empty">${sessions?`${sessions} practice check${sessions===1?'':'s'} completed on this device.`:'Complete a practice check to start building your learning rhythm.'}</p>`;$('.chart-legend').textContent='Progress saved on this device';const heads=document.querySelectorAll('.stat-card .stat-head');if(heads[0])heads[0].firstChild.textContent='COURSEWORK COMPLETE';if(heads[1])heads[1].firstChild.textContent='ACTIVITIES';localStorage.setItem('coachai.activities',JSON.stringify(activities));localStorage.setItem('coachai.sessions',sessions);localStorage.setItem('coachai.mastery',mastery);persistLearnerState()}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const activityDialog=$('#activityDialog');$('#addActivity').onclick=()=>activityDialog.showModal();$('#viewActivities').onclick=()=>document.querySelector('.focus-panel').scrollIntoView({behavior:'smooth',block:'center'});
$('#activityForm').onsubmit=e=>{e.preventDefault();const data=new FormData(e.currentTarget),name=String(data.get('name')).trim();if(!name)return;const palette=[['#88a987','#eff5ed','✳'],['#a99ac2','#f3f0f7','◈'],['#d2a276','#fbf3eb','✦'],['#7da9ab','#edf5f5','◎']][activities.length%4];activities.push({name,caption:String(data.get('goal')||'A new goal · Ready to begin'),score:0,color:palette[0],bg:palette[1],icon:palette[2]});render();e.currentTarget.reset();activityDialog.close()};

// Coursework and due date calendar
const dateKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const offsetDate=n=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return dateKey(d)};
let assignments=read('coachai.assignments',[]);
// Remove only the sample records bundled by the old preview; keep student-created work.
const oldSamples=new Set(['seed-chem','seed-math','seed-bio']);assignments=assignments.filter(a=>!oldSamples.has(a.id));
const sampleCaptions=new Set(['Bonding · Exam in 12 days','Algebra · Building momentum','Cell biology · On track','Vocabulary · Ready to review']);activities=activities.filter(a=>!sampleCaptions.has(a.caption));
if(sessions===8&&mastery===68){sessions=0;mastery=0}
localStorage.setItem('coachai.assignments',JSON.stringify(assignments));localStorage.setItem('coachai.activities',JSON.stringify(activities));localStorage.setItem('coachai.sessions',sessions);localStorage.setItem('coachai.mastery',mastery);
render();
let selectedDay=dateKey(new Date());
function prettyDate(key){return new Intl.DateTimeFormat('en',{weekday:'short',month:'short',day:'numeric'}).format(new Date(`${key}T12:00:00`))}
function daysAway(key){const d=new Date();d.setHours(12,0,0,0);return Math.round((new Date(`${key}T12:00:00`)-d)/86400000)}
function renderAssignments(){const mode=$('#taskFilter').value,shown=assignments.filter(a=>mode==='all'||(mode==='done'?a.done:!a.done)).sort((a,b)=>Number(a.done)-Number(b.done)||a.due.localeCompare(b.due));$('#assignmentList').innerHTML=shown.map(a=>{const n=daysAway(a.due),due=a.done?'Completed':n<0?`${-n}d overdue`:n===0?'Due today':n===1?'Due tomorrow':prettyDate(a.due);return `<div class="assignment-row ${a.done?'is-done':''}"><input class="task-check" type="checkbox" data-task="${escapeHTML(a.id)}" ${a.done?'checked':''} aria-label="Mark task complete"><div><div class="task-title">${escapeHTML(a.title)}</div><div class="task-meta"><span class="task-subject">${escapeHTML(a.subject||'Personal')}</span><span>·</span><span>${escapeHTML(a.duration||'')}</span><span class="priority-pill ${escapeHTML(a.priority)}">${escapeHTML(a.priority)}</span></div></div><div class="task-due ${!a.done&&n<=1?'soon':''}">${escapeHTML(due)}</div><button class="delete-task" type="button" data-delete="${escapeHTML(a.id)}" aria-label="Delete ${escapeHTML(a.title)}" title="Delete task">×</button></div>`}).join('');const open=assignments.filter(a=>!a.done).length;$('#assignmentSummary').textContent=open?`${open} task${open===1?'':'s'} to go · sorted by due date`:'All caught up · add another task when you need to';$('#emptyAssignments').hidden=shown.length>0;$('#assignmentList').hidden=shown.length===0;$('#assignmentList').querySelectorAll('.task-check').forEach(c=>c.onchange=()=>{const a=assignments.find(x=>x.id===c.dataset.task);if(a)a.done=c.checked;saveAssignments()});$('#assignmentList').querySelectorAll('.delete-task').forEach(b=>b.onclick=()=>{assignments=assignments.filter(a=>a.id!==b.dataset.delete);saveAssignments()})}
function renderWeek(){const today=new Date();today.setHours(12,0,0,0);const monday=new Date(today);monday.setDate(today.getDate()-((today.getDay()+6)%7));$('#calendarWeek').innerHTML=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);const k=dateKey(d),has=assignments.some(a=>a.due===k&&!a.done);return `<button class="day-cell ${k===dateKey(today)?'today':''} ${k===selectedDay?'selected':''} ${has?'has-due':''}" data-day="${k}"><span>${new Intl.DateTimeFormat('en',{weekday:'short'}).format(d).toUpperCase()}</span><b>${d.getDate()}</b></button>`}).join('');$('#calendarWeek').querySelectorAll('.day-cell').forEach(b=>b.onclick=()=>{selectedDay=b.dataset.day;renderWeek()});const events=assignments.filter(a=>a.due===selectedDay);$('#calendarEvents').innerHTML=events.length?events.map(a=>`<div class="calendar-event"><i class="event-mark" style="background:${a.priority==='high'?'#cf9471':'#8baa8a'}"></i><span><b>${escapeHTML(a.title)}</b><small>${escapeHTML(a.subject||'Personal')} · ${a.done?'Completed':'Due '+(daysAway(a.due)===0?'today':daysAway(a.due)===1?'tomorrow':prettyDate(a.due))}</small></span><time>${escapeHTML(a.duration||'')}</time></div>`).join(''):`<div class="calendar-empty">Nothing due ${selectedDay===dateKey(today)?'today':'on '+prettyDate(selectedDay)}. A little breathing room.</div>`}
function saveAssignments(){localStorage.setItem('coachai.assignments',JSON.stringify(assignments));renderAssignments();renderWeek();render()}
function renderPlanner(){renderAssignments();renderWeek()}
renderPlanner();
$('#taskFilter').onchange=renderAssignments;$('#addAssignment').onclick=()=>{const f=$('#assignmentForm');f.elements.due.min=dateKey(new Date());f.elements.due.value=offsetDate(1);$('#assignmentDialog').showModal()};$('#closeAssignment').onclick=()=>$('#assignmentDialog').close();$('#calendarToday').onclick=()=>{selectedDay=dateKey(new Date());renderWeek()};
$('#assignmentForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget);assignments.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),title:String(d.get('title')).trim(),subject:String(d.get('subject')).trim(),due:String(d.get('due')),priority:String(d.get('priority')),duration:String(d.get('duration')),notes:String(d.get('notes')||'').trim(),done:false});selectedDay=String(d.get('due'));saveAssignments();e.currentTarget.reset();$('#assignmentDialog').close()};

function getLearnerName(){const raw=localStorage.getItem('coachai.name');if(!raw)return 'Student';try{return JSON.parse(raw)||'Student'}catch{return raw||'Student'}}
function setProfile(){const name=getLearnerName();$('#profileInitial').textContent=(name[0]||'S').toUpperCase();$('#profileName').textContent=name;$('#profileEmail').textContent='Saved on this device';$('#accountButton').textContent='↓';$('#accountButton').title='Download a backup of your data'}
setProfile();
const dateLabel=new Intl.DateTimeFormat('en',{weekday:'long',month:'long',day:'numeric'}).format(new Date()).toUpperCase();$('.welcome .eyebrow').innerHTML=`<span class="sun">☼</span> ${escapeHTML(dateLabel)}`;$('.welcome h1').innerHTML=`Welcome back, ${escapeHTML(getLearnerName())}<span class="wave">✳</span>`;
$('#accountButton').onclick=exportBackup;
$('#openCoach').onclick=()=>$('#coachDialog').showModal();$('#closeCoach').onclick=()=>$('#coachDialog').close();
function addChatBubble(text,kind,save=true){const bubble=document.createElement('div');bubble.className=`chat-bubble ${kind==='user'?'user-bubble':'coach-bubble'}`;bubble.textContent=text;$('#chatMessages').append(bubble);$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight;if(save){chatHistory.push({text,kind});chatHistory=chatHistory.slice(-30);localStorage.setItem('coachai.chat',JSON.stringify(chatHistory))}if(kind==='coach'&&$('#readAloud')?.checked&&'speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text))}return bubble}
chatHistory.forEach(m=>addChatBubble(m.text,m.kind,false));
let learnerProfile={qualification:'Cambridge IGCSE',level:'High school',subject:'Math',topic:'',mode:'learn',...read('coachai.learner',{})};
let topicResults=read('coachai.topicResults',{}),reviewedTopics=read('coachai.reviewed',[]),queuedQuestions=null;
function localCoachReply(message){
 const q=message.toLowerCase(),open=assignments.filter(a=>!a.done).sort((a,b)=>a.due.localeCompare(b.due)),next=open[0];
 if(/explain|teach|what is|what are|how does|help me understand/.test(q)){
  const query=q+' '+learnerProfile.topic.toLowerCase(),topic=/percent|discount|percentage/.test(query)?'percentages':/ratio|share.*amount/.test(query)?'ratio':/diffusion|osmosis|partially permeable/.test(query)?'diffusion-osmosis':/inherit|gene|chromosome|genetic|dna/.test(query)?'inheritance':/cell|organelle|chloroplast|nucleus/.test(query)?'cell-structure':/atomic structure|proton|neutron|electron shell/.test(query)?'atomic-structure':/acid|alkali|neutralis|neutraliz|hydroxide/.test(query)?'acids-alkalis':/rate of reaction|collision|activation energy/.test(query)?'rates-of-reaction':/inference|imply|reading evidence/.test(query)?'reading-inference':/persuad|rhetorical|audience/.test(query)?'persuasive-language':/fraction/.test(query)?'fractions':/photo|plant|chlorophyll/.test(query)?'photosynthesis':/bond|electron|covalent/.test(query)?'covalent-bonds':/thesis|essay|argument/.test(query)?'thesis-statements':/equation|algebra|linear/.test(query)?'linear-equations':(/teach|quiz me|prepare me|help me learn/.test(q)?({Biology:'photosynthesis',Chemistry:'covalent-bonds',English:'thesis-statements',Math:'linear-equations'}[learnerProfile.subject]||null):null);
  const matched=topic;
  if(!matched)return `I don't have a prepared lesson for that exact topic yet. Browse the Cambridge IGCSE starter topics in Math, Biology, Chemistry, and English, or tell me the closest topic you are studying. I can open its explanation, worked example, and practice questions for your ${learnerProfile.level} level.`;
  lessonSelect.value=matched;showLesson();return `${learnerProfile.level} ${learnerProfile.subject} · ${learnerProfile.mode==='test'?'test prep':learnerProfile.mode==='quiz'?'quiz practice':'learning'}: ${lessons[matched].explanation} I opened the matching lesson with a worked example and three practice questions. This helper runs offline and uses prepared explanations.`;
 }
 if(/plan|prioriti|where.*start|what.*first|overwhelm/.test(q)){if(!next)return 'Your coursework list is clear. Add the next thing you need to do, then split it into a small first step.';return `Start with “${next.title}”${next.subject?` for ${next.subject}`:''}, due ${daysAway(next.due)<0?`${-daysAway(next.due)} days ago`:daysAway(next.due)===0?'today':daysAway(next.due)===1?'tomorrow':prettyDate(next.due)}. Try a 20-minute focus block, then write down the next step.`}
 if(/break|start|assignment|essay|project/.test(q))return next?`Make the first step small enough to do in 10 minutes. For “${next.title}”, open the instructions, list what you need, and choose one part to begin.`:'Write down the assignment, its due date, and the very first 10-minute step. Add it to your planner so it stays visible.';
 return next?`You have ${open.length} unfinished task${open.length===1?'':'s'}. Your next due is “${next.title}” (${prettyDate(next.due)}). What is one small step you could do in 10 minutes?`:'What is one small step you can finish in 10 minutes? Add coursework and due dates to your planner to help organize your week.'
}
$('#chatForm').onsubmit=e=>{e.preventDefault();const form=e.currentTarget,field=form.elements.message,message=field.value.trim();if(!message)return;addChatBubble(message,'user');field.value='';addChatBubble(localCoachReply(message),'coach');field.focus()};
const voiceStatus=$('#voiceStatus'),voiceButton=$('#voiceInput'),SpeechRecognitionAPI=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null;
if(!SpeechRecognitionAPI){voiceStatus.textContent='Voice input is not available in this browser. You can still type, and read-aloud may work.';voiceButton.title='Speech recognition is not supported in this browser'}
if(!('speechSynthesis'in window)){$('#readAloud').disabled=true;voiceStatus.textContent=SpeechRecognitionAPI?'Speech input is available. Read-aloud is not supported here.':'Voice input and read-aloud are not supported here. You can still type your questions.'}
voiceButton.onclick=()=>{if(!SpeechRecognitionAPI){voiceStatus.classList.add('is-error');return}if(recognition){recognition.stop();return}recognition=new SpeechRecognitionAPI();recognition.lang='en-US';recognition.interimResults=false;recognition.maxAlternatives=1;voiceButton.textContent='Listening…';voiceStatus.textContent='Listening on this device. Speak now.';recognition.onresult=event=>{const field=$('#chatForm').elements.message;field.value=event.results[0][0].transcript;voiceStatus.textContent='Heard you. Sending your question…';$('#chatForm').requestSubmit()};recognition.onerror=event=>{voiceStatus.textContent=event.error==='not-allowed'?'Microphone access was blocked. Allow it in your browser settings or type your question.':`Voice input stopped (${event.error}). You can type your question instead.`;voiceStatus.classList.add('is-error')};recognition.onend=()=>{recognition=null;voiceButton.textContent='🎙 Speak';if(voiceStatus.textContent.startsWith('Listening'))voiceStatus.textContent='No speech captured. Tap Speak to try again.'};recognition.start()};
function exportBackup(){const data={format:'coach-ai-backup',version:1,createdAt:new Date().toISOString(),assignments,activities,sessions,mastery,studyMinutes,name:getLearnerName(),learnerProfile,topicResults,reviewedTopics,chatHistory};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='coach-ai-backup.json';a.click();URL.revokeObjectURL(url)}
$('#exportData').onclick=exportBackup;$('#accountButton').onclick=exportBackup;
$('#importData').onclick=()=>$('#backupFile').click();
$('#backupFile').onchange=async e=>{
 const file=e.target.files[0];if(!file)return;
 try{
  const data=JSON.parse(await file.text());
  if(data.format!=='coach-ai-backup'||!Array.isArray(data.assignments)||!Array.isArray(data.activities))throw new Error('This file is not a Coach AI backup.');
  assignments=data.assignments;activities=data.activities;sessions=Number(data.sessions)||0;mastery=Number(data.mastery)||0;studyMinutes=Number(data.studyMinutes)||0;chatHistory=Array.isArray(data.chatHistory)?data.chatHistory:[];
  learnerProfile={qualification:'Cambridge IGCSE',level:'High school',subject:'Math',topic:'',mode:'learn',...(data.learnerProfile||{})};topicResults=data.topicResults||{};reviewedTopics=Array.isArray(data.reviewedTopics)?data.reviewedTopics:[];
  localStorage.setItem('coachai.learner',JSON.stringify(learnerProfile));localStorage.setItem('coachai.topicResults',JSON.stringify(topicResults));localStorage.setItem('coachai.reviewed',JSON.stringify(reviewedTopics));localStorage.setItem('coachai.name',JSON.stringify(String(data.name||'Student')));localStorage.setItem('coachai.chat',JSON.stringify(chatHistory));
  learnerForm.elements.qualification.value=learnerProfile.qualification;learnerForm.elements.level.value=learnerProfile.level;learnerForm.elements.subject.value=learnerProfile.subject;learnerForm.elements.topic.value=learnerProfile.topic||'';learnerForm.elements.mode.value=learnerProfile.mode;renderLearnerSummary();saveAssignments();render();setProfile();$('#chatMessages').replaceChildren();chatHistory.forEach(m=>addChatBubble(m.text,m.kind,false));renderResourceLibrary();alert('Backup restored on this device.')
 }catch(err){alert(err.message||'Could not read that backup file.')}finally{e.target.value=''}
};
$('#clearData').onclick=()=>{if(!confirm('Clear all Coach AI data saved in this browser? Export a backup first if you want to keep it.'))return;Object.keys(localStorage).filter(k=>k.startsWith('coachai.')).forEach(k=>localStorage.removeItem(k));location.reload()};

// Guided lessons: explanations, worked examples, retrieval practice, and feedback all run locally.
const lessons={
 'linear-equations':{subject:'MATH · FOUNDATIONS',title:'Solve a linear equation',explanation:'An equation is a balance: both sides have the same value. To find the unknown, use inverse operations to undo what was done to it. Whatever you do to one side, do to the other.',example:'Solve 3x + 5 = 20. Subtract 5 from both sides: 3x = 15. Divide both sides by 3: x = 5. Check: 3(5) + 5 = 20.',takeaway:'The goal is to get the variable alone while keeping the equation balanced.',question:'Solve 2x + 7 = 19. What is x?',answers:['5','6','13','26'],correct:1,feedback:'Subtract 7 first: 2x = 12. Then divide by 2, so x = 6. Check by substituting: 2(6) + 7 = 19.',quiz:[{question:'Solve 3x + 4 = 19.',answers:['3','5','7','15'],correct:1,feedback:'Subtract 4, then divide by 3: x = 5.'},{question:'Solve 4x − 8 = 12.',answers:['1','4','5','20'],correct:2,feedback:'Add 8, then divide by 4: x = 5.'}]},
 'fractions':{subject:'MATH · NUMBER SENSE',title:'Add fractions with unlike denominators',explanation:'The denominator tells you the size of the pieces. You can only add fractions once their pieces are the same size. Find a common denominator, rename each fraction, then add the numerators.',example:'Add 1/3 + 1/4. A common denominator is 12. Rename: 1/3 = 4/12 and 1/4 = 3/12. Add: 4/12 + 3/12 = 7/12.',takeaway:'Make equal-sized pieces first. Add the top numbers and keep the shared denominator.',question:'What is 1/2 + 1/3?',answers:['2/5','5/6','1/6','2/6'],correct:1,feedback:'A common denominator is 6: 1/2 = 3/6 and 1/3 = 2/6. Their sum is 5/6.',quiz:[{question:'What is 1/4 + 1/2?',answers:['2/6','3/4','1/6','3/8'],correct:1,feedback:'Rename 1/2 as 2/4, then add: 3/4.'},{question:'What is 2/3 + 1/6?',answers:['3/9','1/2','5/6','3/6'],correct:2,feedback:'Rename 2/3 as 4/6, then add: 5/6.'}]},
 'photosynthesis':{subject:'BIOLOGY · PLANT SCIENCE',title:'How photosynthesis stores energy',explanation:'Plants use light energy captured by chlorophyll to combine carbon dioxide from air with water. This makes glucose, which stores chemical energy, and releases oxygen. Light provides energy; it is not itself a material ingredient in the products.',example:'carbon dioxide + water + light energy → glucose + oxygen. The process happens mainly in chloroplasts in green plant cells.',takeaway:'Photosynthesis moves energy from sunlight into chemical energy stored in glucose.',question:'Which product stores the captured energy for the plant to use?',answers:['Oxygen','Water','Glucose','Carbon dioxide'],correct:2,feedback:'Glucose stores chemical energy that the plant can use for growth and cell processes. Oxygen is released as a by-product.',quiz:[{question:'Which gas do plants take in for photosynthesis?',answers:['Oxygen','Carbon dioxide','Nitrogen','Hydrogen'],correct:1,feedback:'Plants take in carbon dioxide and release oxygen.'},{question:'Where does most photosynthesis happen in a plant cell?',answers:['Nucleus','Mitochondrion','Chloroplast','Cell wall'],correct:2,feedback:'Chloroplasts contain chlorophyll, which captures light.'}]},
 'covalent-bonds':{subject:'CHEMISTRY · BONDING',title:'Why atoms form covalent bonds',explanation:'Atoms form covalent bonds by sharing pairs of electrons. Sharing can help each atom reach a more stable outer electron arrangement. Covalent bonds commonly form between non-metal atoms.',example:'In a water molecule, oxygen shares electron pairs with two hydrogen atoms. The shared electrons attract both nuclei and hold the atoms together.',takeaway:'Covalent means electrons are shared between atoms.',question:'What happens to electrons in a covalent bond?',answers:['They are shared between atoms','They are transferred to a metal','They disappear','They become protons'],correct:0,feedback:'Exactly: covalent bonds involve shared electron pairs. Electron transfer is associated with ionic bonding.',quiz:[{question:'Covalent bonds most often form between which atoms?',answers:['Two non-metals','Two metals','A metal and a non-metal only','Noble gases only'],correct:0,feedback:'Covalent bonding commonly joins non-metals through shared electrons.'},{question:'Why does sharing electrons hold atoms together?',answers:['Shared electrons attract both nuclei','Atoms lose every electron','Nuclei stop having charge','Electrons become neutrons'],correct:0,feedback:'The shared electrons are attracted to both positive nuclei.'}]},
 'thesis-statements':{subject:'ENGLISH · ARGUMENT WRITING',title:'Build a clear thesis statement',explanation:'A thesis is the main claim your writing will support. A strong thesis answers the prompt, takes a position, and gives the reader a reason or a useful map of the argument. It should be specific enough to support with evidence.',example:'Prompt: Should schools start later? Weak: “School start times are important.” Stronger: “Schools should start later because additional sleep can improve students’ attention and wellbeing.”',takeaway:'Make a debatable claim, then preview why you believe it.',question:'Which is the strongest thesis for an essay about school gardens?',answers:['School gardens are green.','This essay is about gardens.','Schools should grow gardens because they give students hands-on science practice and fresh produce.','Many schools have students.'],correct:2,feedback:'This option takes a clear position and gives two reasons the essay can support with evidence.',quiz:[{question:'What should a strong thesis do?',answers:['List the essay title','Make a specific claim that answers the prompt','Repeat the prompt exactly','Avoid taking a position'],correct:1,feedback:'A thesis makes a focused, supportable claim in response to the prompt.'},{question:'Which detail makes a thesis easier to support?',answers:['A clear reason for the claim','A broad topic only','An unrelated fact','A question with no answer'],correct:0,feedback:'A reason gives the essay a clear argument and helps guide evidence.'}]},
 'percentages':{subject:'MATH · NUMBER',title:'Work with percentages',explanation:'A percentage is a number out of 100. Convert a percentage to a decimal by dividing by 100, then multiply by the amount. For a percentage increase or decrease, find the change and add or subtract it from the original amount.',example:'Find 15% of 80: 0.15 × 80 = 12. A 15% increase on 80 is 80 + 12 = 92.',takeaway:'Convert the percentage to a decimal, multiply, then check whether the question asks for the part or the new total.',question:'What is 20% of 65?',answers:['13','20','32.5','45'],correct:0,feedback:'20% = 0.20, and 0.20 × 65 = 13.',quiz:[{question:'A £50 item is reduced by 10%. What is the sale price?',answers:['£5','£40','£45','£55'],correct:2,feedback:'10% of £50 is £5. Subtract the reduction: £50 − £5 = £45.'},{question:'Write 0.35 as a percentage.',answers:['3.5%','35%','350%','0.35%'],correct:1,feedback:'Multiply a decimal by 100 to write it as a percentage: 0.35 = 35%.'}]},
 'ratio':{subject:'MATH · NUMBER',title:'Share amounts in a ratio',explanation:'A ratio compares quantities in the same order. To share a total, add the ratio parts, divide the total by that sum to find one part, then multiply by each ratio number.',example:'Share 30 in the ratio 2:3. There are 5 parts, so one part is 30 ÷ 5 = 6. The shares are 2 × 6 = 12 and 3 × 6 = 18.',takeaway:'Add the ratio parts first, then find the value of one part.',question:'Share 24 in the ratio 1:3. What is the larger share?',answers:['6','12','18','21'],correct:2,feedback:'There are 4 parts. One part is 24 ÷ 4 = 6, so the larger share is 3 × 6 = 18.',quiz:[{question:'Simplify the ratio 12:8.',answers:['6:4','3:2','2:3','4:3'],correct:1,feedback:'Divide both numbers by their highest common factor, 4: 12:8 = 3:2.'},{question:'A recipe uses flour and sugar in the ratio 5:2. How many parts are there altogether?',answers:['3','5','7','10'],correct:2,feedback:'Add the parts: 5 + 2 = 7.'}]},
 'cell-structure':{subject:'BIOLOGY · CELLS',title:'Compare animal and plant cells',explanation:'Animal and plant cells share a cell membrane, cytoplasm, and a nucleus. Plant cells also have a cellulose cell wall, chloroplasts for photosynthesis, and often a large permanent vacuole containing cell sap.',example:'A leaf cell has chloroplasts to absorb light. A cheek cell has no chloroplasts, but both cells have a nucleus and cell membrane.',takeaway:'Learn the structures both cell types share, then identify the three common plant-cell features.',question:'Which structure is found in a plant cell but not a typical animal cell?',answers:['Cell membrane','Cytoplasm','Cellulose cell wall','Nucleus'],correct:2,feedback:'Plant cells have a cellulose cell wall. Both plant and animal cells have a cell membrane, cytoplasm, and nucleus.',quiz:[{question:'Where is genetic material stored in a typical animal cell?',answers:['Cell wall','Nucleus','Vacuole','Chloroplast'],correct:1,feedback:'The nucleus contains the cell’s genetic material.'},{question:'Which structure is the site of photosynthesis?',answers:['Chloroplast','Ribosome','Cell membrane','Mitochondrion'],correct:0,feedback:'Chloroplasts contain chlorophyll, which absorbs light energy for photosynthesis.'}]},
 'diffusion-osmosis':{subject:'BIOLOGY · MOVEMENT OF SUBSTANCES',title:'Explain diffusion and osmosis',explanation:'Diffusion is the net movement of particles from a region of higher concentration to lower concentration. Osmosis is the net movement of water molecules through a partially permeable membrane from a dilute solution to a more concentrated solution.',example:'Oxygen moves from the air sacs in the lungs, where its concentration is high, into the blood, where its concentration is lower.',takeaway:'For osmosis, include water, a partially permeable membrane, and movement from dilute to more concentrated solution.',question:'Which process describes water moving through a partially permeable membrane?',answers:['Active transport','Diffusion','Osmosis','Respiration'],correct:2,feedback:'Osmosis is the net movement of water molecules through a partially permeable membrane from dilute to more concentrated solution.',quiz:[{question:'In which direction is the net movement of diffusing particles?',answers:['Low to high concentration','High to low concentration','Only into a cell','Only through a membrane'],correct:1,feedback:'Diffusion moves particles down a concentration gradient: from high to low concentration.'},{question:'What type of membrane is needed for osmosis?',answers:['Fully open','Partially permeable','Impermeable','Cellulose only'],correct:1,feedback:'Osmosis requires a partially permeable membrane that lets water molecules pass.'}]},
 'inheritance':{subject:'BIOLOGY · GENETICS',title:'Understand genes and inheritance',explanation:'DNA carries genetic information. A gene is a section of DNA that influences a characteristic, and genes are found on chromosomes. Offspring inherit genetic information from their parents, so they can share features while still showing variation.',example:'A child may inherit an allele for eye colour from each biological parent. The combination of alleles contributes to the child’s genotype and can influence the phenotype.',takeaway:'Keep DNA, genes, chromosomes, genotype, and phenotype distinct when explaining inheritance.',question:'What is a gene?',answers:['A whole cell','A section of DNA with information','A type of protein only','A cell membrane'],correct:1,feedback:'A gene is a section of DNA that carries information used in the development of a characteristic.',quiz:[{question:'Where are genes found?',answers:['On chromosomes','In the cell wall','Only in the cytoplasm','On ribosomes'],correct:0,feedback:'Genes are sections of DNA located on chromosomes.'},{question:'What does phenotype describe?',answers:['The observable characteristics of an organism','Only the inherited alleles','A type of chromosome','The order of cell division'],correct:0,feedback:'Phenotype means the observable characteristics, influenced by genotype and environment.'}]},
 'atomic-structure':{subject:'CHEMISTRY · ATOMS',title:'Describe atomic structure',explanation:'Atoms contain a tiny central nucleus with protons and neutrons. Electrons occupy shells around the nucleus. Protons have a positive charge, electrons a negative charge, and neutrons no charge. In a neutral atom, proton and electron numbers are equal.',example:'A sodium atom has 11 protons and 11 electrons. Its electron arrangement is 2,8,1, so the outer shell contains one electron.',takeaway:'Use proton number to identify the element; in a neutral atom, it also equals the electron number.',question:'Which particle has a negative relative charge?',answers:['Proton','Neutron','Electron','Nucleus'],correct:2,feedback:'Electrons have a negative charge; protons are positive and neutrons have no charge.',quiz:[{question:'Where are protons and neutrons found?',answers:['In electron shells','In the nucleus','Outside the atom','In chemical bonds only'],correct:1,feedback:'Protons and neutrons are located in the nucleus.'},{question:'How many electrons does a neutral atom with 8 protons have?',answers:['0','4','8','16'],correct:2,feedback:'A neutral atom has equal numbers of protons and electrons, so it has 8 electrons.'}]},
 'acids-alkalis':{subject:'CHEMISTRY · ACIDS AND ALKALIS',title:'Describe acids and neutralisation',explanation:'Acids produce hydrogen ions in aqueous solution. Alkalis are soluble bases that produce hydroxide ions. In neutralisation, hydrogen ions react with hydroxide ions to form water; acid-base reactions can also produce a salt.',example:'Hydrochloric acid + sodium hydroxide → sodium chloride + water. The ionic equation is H⁺ + OH⁻ → H₂O.',takeaway:'For neutralisation, remember that hydrogen ions and hydroxide ions make water.',question:'What do hydrogen ions react with during neutralisation?',answers:['Sodium atoms','Hydroxide ions','Electrons','Chloride ions only'],correct:1,feedback:'Hydrogen ions react with hydroxide ions to form water: H⁺ + OH⁻ → H₂O.',quiz:[{question:'What does an alkali produce in aqueous solution?',answers:['Hydroxide ions','Only oxygen','Neutrons','Chlorophyll'],correct:0,feedback:'Alkalis are soluble bases that produce hydroxide ions in water.'},{question:'Which products are formed when an acid reacts with an alkali?',answers:['Salt and water','Metal and oxygen','Hydrogen and carbon','Only water'],correct:0,feedback:'A neutralisation reaction between an acid and alkali forms a salt and water.'}]},
 'rates-of-reaction':{subject:'CHEMISTRY · REACTIONS',title:'Explain rates of reaction',explanation:'Reaction rate describes how quickly reactants are used up or products form. Particles must collide with enough energy to react. A higher temperature, greater concentration, higher gas pressure, or larger solid surface area can increase the frequency of successful collisions.',example:'Powdered calcium carbonate reacts faster than the same mass of large chips because the powder exposes more surface area for collisions.',takeaway:'Link a change in conditions to collision frequency or the energy of collisions.',question:'Why does powdered solid often react faster than large chips?',answers:['It has a lower mass','It exposes a larger surface area','It has fewer particles','It stops particles colliding'],correct:1,feedback:'Powder exposes more surface area, so reactant particles can collide with it more often.',quiz:[{question:'What must particles do for a reaction to occur?',answers:['Collide with enough energy','Stop moving','Lose all their electrons','Become colder'],correct:0,feedback:'A successful collision needs enough energy to overcome the activation energy.'},{question:'What usually happens to reaction rate when temperature increases?',answers:['It decreases to zero','It stays fixed','It increases','The reactants disappear instantly'],correct:2,feedback:'Higher temperature makes particles move faster, increasing successful collisions per second.'}]},
 'reading-inference':{subject:'ENGLISH · READING',title:'Support an inference with evidence',explanation:'An inference is a reasoned idea about what a writer implies. Combine a detail from the text with what that detail suggests; do not just repeat the detail or claim something the text cannot support.',example:'Text: “Maya checked the dark street twice, then tightened her grip on the letter.” Inference: Maya may feel nervous about delivering the letter. Evidence: she checks the street and grips it tightly.',takeaway:'Make a clear inference, choose precise evidence, and explain how the evidence supports your idea.',question:'A character “kept glancing at the clock and tapping her foot.” What is a reasonable inference?',answers:['She is waiting impatiently','She has fallen asleep','She is reading a book','She is underwater'],correct:0,feedback:'Looking at the clock and tapping a foot can suggest impatience, though context should guide the final interpretation.',quiz:[{question:'What should support an inference?',answers:['A relevant detail from the text','A guess unrelated to the passage','Only the title','A copied sentence with no explanation'],correct:0,feedback:'Use a relevant textual detail and explain what it suggests.'},{question:'Which is the strongest evidence?',answers:['A precise phrase linked to the inference','A detail from another story','A personal opinion only','A sentence that contradicts the inference'],correct:0,feedback:'Precise evidence makes the reasoning clear and checkable.'}]},
 'persuasive-language':{subject:'ENGLISH · WRITING',title:'Choose persuasive language carefully',explanation:'Persuasive writing aims to influence an audience. A clear position, relevant reasons, evidence, and an appropriate tone usually matter more than piling up techniques. Rhetorical questions, direct address, and emotive wording can help when they suit the purpose.',example:'“Should our town waste usable food? A weekly community collection could help families and reduce landfill.” The question engages readers; the proposal gives a specific action and reasons.',takeaway:'Match the language to the audience and purpose, and make each point support your argument.',question:'Which sentence gives the clearest specific proposal?',answers:['Things should get better.','The council should add two shaded benches to the park this summer.','Parks are nice.','Wouldn’t it be good if something happened?'],correct:1,feedback:'It names who should act, what should change, where, and when.',quiz:[{question:'What is a good reason to use a rhetorical question?',answers:['To engage the intended audience','To replace every piece of evidence','To make the topic unclear','To avoid stating a position'],correct:0,feedback:'A rhetorical question can engage readers when it fits the audience and purpose.'},{question:'What should persuasive evidence do?',answers:['Support the claim','Distract from the claim','Repeat the title','Replace the conclusion'],correct:0,feedback:'Evidence should be relevant to and support the argument.'}]}
};
const lessonSelect=$('#lessonSelect');let activeLesson=null,lessonAnswered=false,quizQuestions=[],quizIndex=0,quizScore=0;
function renderQuizQuestion(){lessonAnswered=false;const q=quizQuestions[quizIndex];$('#lessonQuestion').textContent=q.topicTitle?`${q.topicTitle}: ${q.question}`:q.question;$('#quizProgress').textContent=`Question ${quizIndex+1} of ${quizQuestions.length} · Score ${quizScore}`;$('#lessonAnswers').replaceChildren(...q.answers.map((answer,i)=>{const b=document.createElement('button');b.type='button';b.className='lesson-answer';b.textContent=answer;b.onclick=()=>checkLessonAnswer(i);return b}));$('#lessonFeedback').textContent='';$('#lessonFeedback').className='lesson-feedback';$('#lessonAgain').hidden=true}
function showLesson(){activeLesson=lessons[lessonSelect.value]||lessons['linear-equations'];quizQuestions=queuedQuestions||[{question:activeLesson.question,answers:activeLesson.answers,correct:activeLesson.correct,feedback:activeLesson.feedback,topicKey:lessonSelect.value},...(activeLesson.quiz||[]).map(q=>({...q,topicKey:lessonSelect.value}))];queuedQuestions=null;quizIndex=0;quizScore=0;$('#lessonSubject').textContent=`${learnerProfile.qualification} · ${activeLesson.subject} · ${learnerProfile.level.toUpperCase()}`;$('#lessonTitle').textContent=activeLesson.title;const scaffold=learnerProfile.level==='Upper primary'?'Let’s break it into small, clear steps. ':learnerProfile.level==='Middle school'?'Track each step and check your thinking as you go. ':learnerProfile.level==='College / adult'?'Focus on the underlying principle and how to apply it. ':'Focus on the method and be ready to explain why each step works. ';$('#lessonExplanation').textContent=scaffold+activeLesson.explanation;$('#lessonExample').textContent=activeLesson.example;$('#lessonTakeaway').textContent=learnerProfile.mode==='test'?`Test focus: ${activeLesson.takeaway} Practise explaining each step without looking at the example.`:activeLesson.takeaway;$('#practiceLabel').textContent=learnerProfile.mode==='quiz'?'QUIZ MODE · NO NOTES':learnerProfile.mode==='test'?'TEST PRACTICE':'YOUR TURN';renderQuizQuestion();$('#lessonEmpty').hidden=true;$('#lessonPractice').hidden=learnerProfile.mode!=='quiz';$('#lessonContent').hidden=learnerProfile.mode==='quiz'}
function checkLessonAnswer(index){if(lessonAnswered)return;lessonAnswered=true;const q=quizQuestions[quizIndex],correct=index===q.correct;if(correct)quizScore++;const result=topicResults[q.topicKey]||(topicResults[q.topicKey]={attempts:0,correct:0});result.attempts++;if(correct)result.correct++;localStorage.setItem('coachai.topicResults',JSON.stringify(topicResults));const buttons=$('#lessonAnswers').querySelectorAll('button');buttons.forEach((b,i)=>{b.disabled=true;if(i===q.correct)b.classList.add('correct');else if(i===index)b.classList.add('incorrect')});$('#lessonFeedback').textContent=(correct?'Correct. ':'Not quite. ')+q.feedback;$('#lessonFeedback').classList.add(correct?'is-correct':'is-review');$('#quizProgress').textContent=`Question ${quizIndex+1} of ${quizQuestions.length} · Score ${quizScore}`;$('#lessonAgain').textContent=quizIndex<quizQuestions.length-1?'Next question':'Try another lesson';$('#lessonAgain').hidden=false;sessions+=1;if(correct)mastery=Math.min(100,mastery+4);persistLearnerState();render();renderResourceLibrary()}
$('#beginLesson').onclick=showLesson;lessonSelect.onchange=()=>{if(activeLesson)showLesson()};$('#startLessonPractice').onclick=()=>{$('#lessonContent').hidden=true;$('#lessonPractice').hidden=false};$('#lessonAgain').onclick=()=>{if(quizIndex<quizQuestions.length-1){quizIndex++;renderQuizQuestion();$('#lessonAgain').textContent='Next question'}else{lessonSelect.selectedIndex=(lessonSelect.selectedIndex+1)%lessonSelect.options.length;showLesson()}};
const learnerForm=$('#learnerForm');
learnerForm.elements.qualification.value=learnerProfile.qualification;learnerForm.elements.level.value=learnerProfile.level;learnerForm.elements.subject.value=learnerProfile.subject;learnerForm.elements.topic.value=learnerProfile.topic||'';learnerForm.elements.mode.value=learnerProfile.mode;
function renderLearnerSummary(){const goal=learnerProfile.mode==='test'?'Preparing for a test':learnerProfile.mode==='quiz'?'Quiz practice':'Learning a topic';$('#learnerSummary').textContent=`${learnerProfile.qualification} · ${learnerProfile.level} · ${learnerProfile.subject}${learnerProfile.topic?` · ${learnerProfile.topic}`:''} · ${goal}. Saved only in this browser.`}
renderLearnerSummary();
learnerForm.onsubmit=e=>{e.preventDefault();const data=new FormData(learnerForm);learnerProfile={qualification:String(data.get('qualification')),level:String(data.get('level')),subject:String(data.get('subject')),topic:String(data.get('topic')).trim(),mode:String(data.get('mode'))};localStorage.setItem('coachai.learner',JSON.stringify(learnerProfile));renderLearnerSummary();const topic=learnerProfile.topic.toLowerCase();const suggested=/fraction/.test(topic)?'fractions':/photo|plant/.test(topic)?'photosynthesis':/bond|electron/.test(topic)?'covalent-bonds':/thesis|essay/.test(topic)?'thesis-statements':/equation|algebra/.test(topic)?'linear-equations':learnerProfile.subject==='Biology'?'photosynthesis':learnerProfile.subject==='Chemistry'?'covalent-bonds':learnerProfile.subject==='English'?'thesis-statements':lessonSelect.value;lessonSelect.value=suggested;$('#learnerSummary').textContent+=` Suggested lesson: ${lessons[suggested].title}.`;if(activeLesson)showLesson();renderResourceLibrary()};
function goToLessons(start=false){$('#learn').scrollIntoView({behavior:'smooth',block:'start'});if(start)showLesson()}
$('#startLessonShortcut').onclick=()=>goToLessons(true);$('#nextArrow').onclick=()=>goToLessons(true);
// Profile is a local display name, not an account or email address.
$('#profileButton').onclick=()=>{const current=getLearnerName();const next=prompt('What name should Coach AI use?',current);if(next===null)return;const name=next.trim().slice(0,40)||'Student';localStorage.setItem('coachai.name',JSON.stringify(name));setProfile();$('.welcome h1').innerHTML=`Welcome back, ${escapeHTML(name)}<span class="wave">✳</span>`};
// Quick access to due dates and the planner.
const notificationsDialog=$('#notificationsDialog');$('#notificationsButton').onclick=()=>{const upcoming=assignments.filter(a=>!a.done).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,5);$('#notificationList').innerHTML=upcoming.length?upcoming.map(a=>`<div class="notification-item"><b>${escapeHTML(a.title)}</b><small>${escapeHTML(a.subject||'Personal')} · ${escapeHTML(daysAway(a.due)<0?`${-daysAway(a.due)} days overdue`:daysAway(a.due)===0?'Due today':daysAway(a.due)===1?'Due tomorrow':prettyDate(a.due))}</small></div>`).join(''):'<p class="calendar-empty">No upcoming coursework. Add a due date in your planner to see it here.</p>';notificationsDialog.showModal()};$('#closeNotifications').onclick=()=>notificationsDialog.close();$('#notificationsPlanner').onclick=()=>{notificationsDialog.close();$('#planner').scrollIntoView({behavior:'smooth',block:'start'})};
$('#jumpToday').onclick=()=>{selectedDay=dateKey(new Date());renderWeek();$('#planner').scrollIntoView({behavior:'smooth',block:'start'})};
document.querySelectorAll('.nav-item[href^="#"]').forEach(link=>link.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('active',item===link))}));

// Syllabus-style resource library with locally adaptive topic suggestions.
const resourceSubjects={'linear-equations':'Math',fractions:'Math',percentages:'Math',ratio:'Math',photosynthesis:'Biology','cell-structure':'Biology','diffusion-osmosis':'Biology',inheritance:'Biology','covalent-bonds':'Chemistry','atomic-structure':'Chemistry','acids-alkalis':'Chemistry','rates-of-reaction':'Chemistry','thesis-statements':'English','reading-inference':'English','persuasive-language':'English'};
let resourceTopic=null,flashcardTopic=null,flashcardIndex=0,flashcardBack=false;
function topicAccuracy(id){const score=topicResults[id];return score?.attempts?score.correct/score.attempts:null}
function topicStatus(id){const score=topicResults[id],accuracy=topicAccuracy(id);if(score?.attempts>=2&&accuracy<.6)return 'Review suggested';if(score?.attempts)return `${Math.round(accuracy*100)}% practice accuracy`;if(reviewedTopics.includes(id))return 'Notes reviewed';return 'New topic'}
function renderResourceLibrary(){
 const grid=$('#resourceGrid'),active=document.querySelector('.resource-tab.active')?.dataset.resource||'notes',subject=$('#resourceSubjectFilter').value,search=$('#resourceSearch').value.trim().toLowerCase();
 const topics=Object.keys(lessons).filter(id=>(subject==='all'||resourceSubjects[id]===subject)&&(`${lessons[id].title} ${resourceSubjects[id]} ${lessons[id].subject}`).toLowerCase().includes(search));
 $('#resourceReader').hidden=true;$('#flashcardStage').hidden=true;$('#coachResourcePanel').hidden=active!=='coach';grid.hidden=active==='coach';
 if(active==='coach')return;
 topics.sort((a,b)=>{const aa=topicAccuracy(a),bb=topicAccuracy(b);if(aa===null&&bb===null)return lessons[a].title.localeCompare(lessons[b].title);if(aa===null)return 1;if(bb===null)return -1;return aa-bb});
 grid.innerHTML=topics.length?topics.map(id=>{const l=lessons[id],kind=active==='notes'?'Revision notes':active==='questions'?'3 topic questions':'3 flashcards',action=active==='notes'?'Open notes':active==='questions'?'Start questions':'Open flashcards';return `<article class="panel topic-card"><div class="topic-card-top"><span class="banner-tag">${escapeHTML(resourceSubjects[id])} · ${escapeHTML(learnerProfile.qualification)}</span><span class="topic-status ${topicStatus(id)==='Review suggested'?'needs-review':''}">${escapeHTML(topicStatus(id))}</span></div><h3>${escapeHTML(l.title)}</h3><p>${escapeHTML(l.takeaway)}</p><div class="topic-card-meta"><span>${kind}</span><span>Worked example</span></div><button class="primary-btn" type="button" data-topic="${id}" data-action="${active}">${action} <span>→</span></button></article>`}).join(''):'<div class="calendar-empty">No topics match this filter yet. Try another subject or search.</div>';
 grid.querySelectorAll('[data-topic]').forEach(button=>button.onclick=()=>openResource(button.dataset.topic,button.dataset.action));
}
function openResource(id,kind){resourceTopic=id;const l=lessons[id];if(kind==='notes'){$('#resourceMeta').textContent=`${learnerProfile.qualification} · ${resourceSubjects[id]} · STARTER NOTES`;$('#resourceTitle').textContent=l.title;$('#resourceExplanation').textContent=l.explanation;$('#resourceExample').textContent=l.example;$('#resourceTakeaway').textContent=l.takeaway;$('#markReviewed').textContent=reviewedTopics.includes(id)?'Notes reviewed ✓':'Mark notes reviewed';$('#resourceReader').hidden=false;$('#resourceReader').scrollIntoView({behavior:'smooth',block:'center'});return}
 if(kind==='questions'){startTopicQuiz(id);return}
 flashcardTopic=id;flashcardIndex=0;flashcardBack=false;renderFlashcard();$('#flashcardStage').hidden=false;$('#flashcardStage').scrollIntoView({behavior:'smooth',block:'center'})
}
$('#resourceSubjectFilter').onchange=renderResourceLibrary;$('#resourceSearch').oninput=renderResourceLibrary;
document.querySelectorAll('.resource-tab').forEach(button=>button.onclick=()=>{document.querySelectorAll('.resource-tab').forEach(tab=>{tab.classList.toggle('active',tab===button);tab.setAttribute('aria-selected',String(tab===button))});renderResourceLibrary()});
$('#closeResource').onclick=()=>{$('#resourceReader').hidden=true;$('#resourceGrid').scrollIntoView({behavior:'smooth',block:'center'})};$('#markReviewed').onclick=()=>{if(resourceTopic&&!reviewedTopics.includes(resourceTopic))reviewedTopics.push(resourceTopic);localStorage.setItem('coachai.reviewed',JSON.stringify(reviewedTopics));$('#markReviewed').textContent='Notes reviewed ✓';const card=[...$('#resourceGrid').querySelectorAll('[data-topic]')].find(b=>b.dataset.topic===resourceTopic)?.closest('.topic-card'),status=card?.querySelector('.topic-status');if(status)status.textContent=topicStatus(resourceTopic)};
function startTopicQuiz(id){lessonSelect.value=id;learnerProfile.mode='quiz';learnerForm.elements.mode.value='quiz';localStorage.setItem('coachai.learner',JSON.stringify(learnerProfile));renderLearnerSummary();showLesson();$('#learn').scrollIntoView({behavior:'smooth',block:'start'})}
function startTargetTest(){const subject=$('#resourceSubjectFilter').value,ids=Object.keys(lessons).filter(id=>subject==='all'||resourceSubjects[id]===subject).sort((a,b)=>(topicAccuracy(a)??1.1)-(topicAccuracy(b)??1.1));if(!ids.length)return;const test=[];ids.forEach(id=>{const l=lessons[id],set=[{question:l.question,answers:l.answers,correct:l.correct,feedback:l.feedback},...(l.quiz||[])];set.slice(0,subject==='all'?1:3).forEach(q=>test.push({...q,topicKey:id,topicTitle:l.title}))});lessonSelect.value=ids[0];learnerProfile.subject=subject==='all'?learnerProfile.subject:subject;learnerProfile.mode='quiz';learnerForm.elements.subject.value=learnerProfile.subject;learnerForm.elements.mode.value='quiz';localStorage.setItem('coachai.learner',JSON.stringify(learnerProfile));renderLearnerSummary();queuedQuestions=test;showLesson();$('#learn').scrollIntoView({behavior:'smooth',block:'start'})}
$('#targetTestButton').onclick=startTargetTest;
function flashcardsFor(id){const l=lessons[id];return [{front:'Core idea',back:l.explanation},{front:'Worked example',back:l.example},{front:'Remember this',back:l.takeaway}]}
function renderFlashcard(){const cards=flashcardsFor(flashcardTopic),card=cards[flashcardIndex];$('#flashcardMeta').textContent=`${learnerProfile.qualification} · ${resourceSubjects[flashcardTopic]} · FLASHCARD`;$('#flashcardTopic').textContent=lessons[flashcardTopic].title;$('#flashcardCount').textContent=`CARD ${flashcardIndex+1} OF ${cards.length}`;$('#flashcardText').textContent=flashcardBack?card.back:card.front;$('#flashcardFlip').classList.toggle('is-back',flashcardBack);$('#flashcardPrev').disabled=flashcardIndex===0;$('#flashcardNext').textContent=flashcardIndex===cards.length-1?'Finish cards ✓':'Next card →'}
$('#flashcardFlip').onclick=()=>{flashcardBack=!flashcardBack;renderFlashcard()};$('#flashcardPrev').onclick=()=>{if(flashcardIndex>0){flashcardIndex--;flashcardBack=false;renderFlashcard()}};$('#flashcardNext').onclick=()=>{const count=flashcardsFor(flashcardTopic).length;if(flashcardIndex<count-1){flashcardIndex++;flashcardBack=false;renderFlashcard()}else{$('#flashcardStage').hidden=true;reviewedTopics.includes(flashcardTopic)||reviewedTopics.push(flashcardTopic);localStorage.setItem('coachai.reviewed',JSON.stringify(reviewedTopics));renderResourceLibrary()}};$('#closeFlashcards').onclick=()=>{$('#flashcardStage').hidden=true;renderResourceLibrary()};
$('#resourceStartTest').onclick=()=>startTopicQuiz(resourceTopic);$('#resourceAskCoach').onclick=()=>{const field=$('#chatForm').elements.message;field.value=`Explain ${lessons[resourceTopic].title} for a ${learnerProfile.level} ${learnerProfile.qualification} student.`;$('#coachDialog').showModal();field.focus()};$('#openLibraryCoach').onclick=()=>{const field=$('#chatForm').elements.message;field.value=learnerProfile.topic?`Help me study ${learnerProfile.topic} for my ${learnerProfile.qualification} course.`:'';$('#coachDialog').showModal();field.focus()};
renderResourceLibrary();
