const starterActivities=[];
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback}catch{return fallback}};
let activities=read('coachai.activities',starterActivities),sessions=read('coachai.sessions',0),mastery=read('coachai.mastery',0);
let studyMinutes=read('coachai.minutes',0), chatHistory=read('coachai.chat',[]);
const $=s=>document.querySelector(s),activityLinks=$('#activityLinks'),focusList=$('#focusList');
function persistLearnerState(){localStorage.setItem('coachai.activities',JSON.stringify(activities));localStorage.setItem('coachai.sessions',sessions);localStorage.setItem('coachai.mastery',mastery);localStorage.setItem('coachai.minutes',studyMinutes)}
function render(){activityLinks.innerHTML=activities.map(a=>`<div class="activity-link"><i class="activity-dot" style="background:${a.color}"></i>${escapeHTML(a.name)}</div>`).join('');focusList.innerHTML=activities.length?activities.slice(0,3).map(a=>`<div class="focus-row"><div class="focus-icon" style="background:${a.bg};color:${a.color}">${a.icon}</div><div><div class="focus-name">${escapeHTML(a.name)}</div><div class="focus-caption">${escapeHTML(a.caption)}</div><div class="focus-bar"><i style="width:${a.score}%;background:${a.color}"></i></div></div><div class="focus-score">${a.score}%</div></div>`).join(''):'<div class="calendar-empty">Add a subject or activity to track your learning here.</div>';const sessionStat=document.querySelector('.stat-card:nth-child(3) .stat-value');if(sessionStat)sessionStat.innerHTML=`${sessions}<span class="subvalue"> total</span>`;const badge=document.querySelector('.nav-item em');if(badge)badge.textContent=activities.length;const values=document.querySelectorAll('.stat-card .stat-value');if(values[0])values[0].innerHTML=`${assignments.filter(a=>a.done).length}<span> / ${assignments.length} tasks</span>`;if(values[1])values[1].innerHTML=`${activities.length}<span class="percent"> subjects</span>`;const cards=document.querySelectorAll('.stat-card');cards[0].querySelector('.stat-foot').textContent=assignments.length?`${assignments.filter(a=>!a.done).length} remaining · ${assignments.filter(a=>a.done).length} completed`:'Add coursework to see progress';cards[1].querySelector('.stat-foot').textContent=activities.length?'Your subjects and goals':'Add a subject to start tracking';cards[2].querySelector('.stat-foot').textContent='Practice checks completed';$('.chart-area').innerHTML=`<p class="calendar-empty">${sessions?`${sessions} practice check${sessions===1?'':'s'} completed on this device.`:'Complete a practice check to start building your learning rhythm.'}</p>`;$('.chart-legend').textContent='Progress saved on this device';const heads=document.querySelectorAll('.stat-card .stat-head');if(heads[0])heads[0].firstChild.textContent='COURSEWORK COMPLETE';if(heads[1])heads[1].firstChild.textContent='ACTIVITIES';localStorage.setItem('coachai.activities',JSON.stringify(activities));localStorage.setItem('coachai.sessions',sessions);localStorage.setItem('coachai.mastery',mastery);persistLearnerState()}
function escapeHTML(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const activityDialog=$('#activityDialog');$('#addActivity').onclick=()=>activityDialog.showModal();$('#viewActivities').onclick=()=>document.querySelector('.focus-panel').scrollIntoView({behavior:'smooth',block:'center'});
$('#activityForm').onsubmit=e=>{e.preventDefault();const data=new FormData(e.currentTarget),name=String(data.get('name')).trim();if(!name)return;const palette=[['#88a987','#eff5ed','✳'],['#a99ac2','#f3f0f7','◈'],['#d2a276','#fbf3eb','✦'],['#7da9ab','#edf5f5','◎']][activities.length%4];activities.push({name,caption:String(data.get('goal')||'A new goal · Ready to begin'),score:0,color:palette[0],bg:palette[1],icon:palette[2]});render();e.currentTarget.reset();activityDialog.close()};

// Coursework and due date calendar
const dateKey=d=>{const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,'0')}-${String(x.getDate()).padStart(2,'0')}`};
const offsetDate=n=>{const d=new Date();d.setHours(12,0,0,0);d.setDate(d.getDate()+n);return dateKey(d)};
let assignments=read('coachai.assignments',[]);
// Remove only the sample records bundled by the old preview; keep student-created work.
const oldSamples=new Set(['seed-chem','seed-math','seed-bio']);assignments=assignments.filter(a=>!oldSamples.has(a.id));
const sampleCaptions=new Set(['Bonding · Exam in 12 days','Algebra · Building momentum','Cell biology · On track','Vocabulary · Ready to review']);activities=activities.filter(a=>!sampleCaptions.has(a.caption));
if(sessions===8&&mastery===68){sessions=0;mastery=0}
localStorage.setItem('coachai.assignments',JSON.stringify(assignments));localStorage.setItem('coachai.activities',JSON.stringify(activities));localStorage.setItem('coachai.sessions',sessions);localStorage.setItem('coachai.mastery',mastery);
render();
let selectedDay=dateKey(new Date());
function prettyDate(key){return new Intl.DateTimeFormat('en',{weekday:'short',month:'short',day:'numeric'}).format(new Date(`${key}T12:00:00`))}
function daysAway(key){const d=new Date();d.setHours(12,0,0,0);return Math.round((new Date(`${key}T12:00:00`)-d)/86400000)}
function renderAssignments(){const mode=$('#taskFilter').value,shown=assignments.filter(a=>mode==='all'||(mode==='done'?a.done:!a.done)).sort((a,b)=>Number(a.done)-Number(b.done)||a.due.localeCompare(b.due));$('#assignmentList').innerHTML=shown.map(a=>{const n=daysAway(a.due),due=a.done?'Completed':n<0?`${-n}d overdue`:n===0?'Due today':n===1?'Due tomorrow':prettyDate(a.due);return `<div class="assignment-row ${a.done?'is-done':''}"><input class="task-check" type="checkbox" data-task="${escapeHTML(a.id)}" ${a.done?'checked':''} aria-label="Mark task complete"><div><div class="task-title">${escapeHTML(a.title)}</div><div class="task-meta"><span class="task-subject">${escapeHTML(a.subject||'Personal')}</span><span>·</span><span>${escapeHTML(a.duration||'')}</span><span class="priority-pill ${escapeHTML(a.priority)}">${escapeHTML(a.priority)}</span></div></div><div class="task-due ${!a.done&&n<=1?'soon':''}">${escapeHTML(due)}</div><button class="delete-task" type="button" data-delete="${escapeHTML(a.id)}" aria-label="Delete ${escapeHTML(a.title)}" title="Delete task">×</button></div>`}).join('');const open=assignments.filter(a=>!a.done).length;$('#assignmentSummary').textContent=open?`${open} task${open===1?'':'s'} to go · sorted by due date`:'All caught up · add another task when you need to';$('#emptyAssignments').hidden=shown.length>0;$('#assignmentList').hidden=shown.length===0;$('#assignmentList').querySelectorAll('.task-check').forEach(c=>c.onchange=()=>{const a=assignments.find(x=>x.id===c.dataset.task);if(a)a.done=c.checked;saveAssignments()});$('#assignmentList').querySelectorAll('.delete-task').forEach(b=>b.onclick=()=>{assignments=assignments.filter(a=>a.id!==b.dataset.delete);saveAssignments()})}
function renderWeek(){const today=new Date();today.setHours(12,0,0,0);const monday=new Date(today);monday.setDate(today.getDate()-((today.getDay()+6)%7));$('#calendarWeek').innerHTML=Array.from({length:7},(_,i)=>{const d=new Date(monday);d.setDate(monday.getDate()+i);const k=dateKey(d),has=assignments.some(a=>a.due===k&&!a.done);return `<button class="day-cell ${k===dateKey(today)?'today':''} ${k===selectedDay?'selected':''} ${has?'has-due':''}" data-day="${k}"><span>${new Intl.DateTimeFormat('en',{weekday:'short'}).format(d).toUpperCase()}</span><b>${d.getDate()}</b></button>`}).join('');$('#calendarWeek').querySelectorAll('.day-cell').forEach(b=>b.onclick=()=>{selectedDay=b.dataset.day;renderWeek()});const events=assignments.filter(a=>a.due===selectedDay);$('#calendarEvents').innerHTML=events.length?events.map(a=>`<div class="calendar-event"><i class="event-mark" style="background:${a.priority==='high'?'#cf9471':'#8baa8a'}"></i><span><b>${escapeHTML(a.title)}</b><small>${escapeHTML(a.subject||'Personal')} · ${a.done?'Completed':'Due '+(daysAway(a.due)===0?'today':daysAway(a.due)===1?'tomorrow':prettyDate(a.due))}</small></span><time>${escapeHTML(a.duration||'')}</time></div>`).join(''):`<div class="calendar-empty">Nothing due ${selectedDay===dateKey(today)?'today':'on '+prettyDate(selectedDay)}. A little breathing room.</div>`}
function saveAssignments(){localStorage.setItem('coachai.assignments',JSON.stringify(assignments));renderAssignments();renderWeek();render()}
function renderPlanner(){renderAssignments();renderWeek()}
renderPlanner();
$('#taskFilter').onchange=renderAssignments;$('#addAssignment').onclick=()=>{const f=$('#assignmentForm');f.elements.due.min=dateKey(new Date());f.elements.due.value=offsetDate(1);$('#assignmentDialog').showModal()};$('#closeAssignment').onclick=()=>$('#assignmentDialog').close();$('#calendarToday').onclick=()=>{selectedDay=dateKey(new Date());renderWeek()};
$('#assignmentForm').onsubmit=e=>{e.preventDefault();const d=new FormData(e.currentTarget);assignments.push({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),title:String(d.get('title')).trim(),subject:String(d.get('subject')).trim(),due:String(d.get('due')),priority:String(d.get('priority')),duration:String(d.get('duration')),notes:String(d.get('notes')||'').trim(),done:false});selectedDay=String(d.get('due'));saveAssignments();e.currentTarget.reset();$('#assignmentDialog').close()};

function getLearnerName(){const raw=localStorage.getItem('coachai.name');if(!raw)return 'Student';try{return JSON.parse(raw)||'Student'}catch{return raw||'Student'}}
function setProfile(){const name=getLearnerName();$('#profileInitial').textContent=(name[0]||'S').toUpperCase();$('#profileName').textContent=name;$('#profileEmail').textContent='Saved on this device';$('#accountButton').textContent='↓';$('#accountButton').title='Download a backup of your data'}
setProfile();
const dateLabel=new Intl.DateTimeFormat('en',{weekday:'long',month:'long',day:'numeric'}).format(new Date()).toUpperCase();$('.welcome .eyebrow').innerHTML=`<span class="sun">☼</span> ${escapeHTML(dateLabel)}`;$('.welcome h1').innerHTML=`Welcome back, ${escapeHTML(getLearnerName())}<span class="wave">✳</span>`;
$('#accountButton').onclick=exportBackup;
$('#openCoach').onclick=()=>$('#coachDialog').showModal();$('#closeCoach').onclick=()=>$('#coachDialog').close();
function addChatBubble(text,kind,save=true){const bubble=document.createElement('div');bubble.className=`chat-bubble ${kind==='user'?'user-bubble':'coach-bubble'}`;bubble.textContent=text;$('#chatMessages').append(bubble);$('#chatMessages').scrollTop=$('#chatMessages').scrollHeight;if(save){chatHistory.push({text,kind});chatHistory=chatHistory.slice(-30);localStorage.setItem('coachai.chat',JSON.stringify(chatHistory))}if(kind==='coach'&&$('#readAloud')?.checked&&'speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text))}return bubble}
chatHistory.forEach(m=>addChatBubble(m.text,m.kind,false));
let learnerProfile=read('coachai.learner',{level:'High school',subject:'Math',topic:'',mode:'learn'});
function localCoachReply(message){
 const q=message.toLowerCase(),open=assignments.filter(a=>!a.done).sort((a,b)=>a.due.localeCompare(b.due)),next=open[0];
 if(/explain|teach|what is|what are|how does|help me understand/.test(q)){
  const query=q+' '+learnerProfile.topic.toLowerCase(),topic=/fraction/.test(query)?'fractions':/photo|plant|chlorophyll/.test(query)?'photosynthesis':/bond|electron|covalent/.test(query)?'covalent-bonds':/thesis|essay|argument/.test(query)?'thesis-statements':/equation|algebra|linear/.test(query)?'linear-equations':(/teach|quiz me|prepare me|help me learn/.test(q)?({Biology:'photosynthesis',Chemistry:'covalent-bonds',English:'thesis-statements',Math:'linear-equations'}[learnerProfile.subject]||null):null);
  const mini={fractions:'To add fractions, rename them with a common denominator first. For example, 1/2 + 1/3 = 3/6 + 2/6 = 5/6.',photosynthesis:'Photosynthesis uses light energy to turn carbon dioxide and water into glucose and oxygen. The glucose stores energy for the plant.','covalent-bonds':'A covalent bond forms when atoms share electron pairs. This shared attraction holds the atoms together.','thesis-statements':'A thesis is a specific, supportable claim that answers the prompt and previews the reasons your writing will defend.','linear-equations':'Solve a linear equation by undoing operations in reverse order while doing the same thing to both sides.'};
  const matched=topic;
  if(!matched)return `I don't have a prepared lesson for that topic yet. My current lessons cover linear equations, fractions, photosynthesis, covalent bonds, and thesis statements. Tell me which ${learnerProfile.subject} topic you are studying and I’ll walk through an example at your ${learnerProfile.level} level.`;
  lessonSelect.value=matched;showLesson();return `${learnerProfile.level} ${learnerProfile.subject} · ${learnerProfile.mode==='test'?'test prep':learnerProfile.mode==='quiz'?'quiz practice':'learning'}: ${mini[matched]} I opened a short lesson with a worked example and a three-question practice set below. This helper runs offline and uses prepared explanations.`;
 }
 if(/plan|prioriti|where.*start|what.*first|overwhelm/.test(q)){if(!next)return 'Your coursework list is clear. Add the next thing you need to do, then split it into a small first step.';return `Start with “${next.title}”${next.subject?` for ${next.subject}`:''}, due ${daysAway(next.due)<0?`${-daysAway(next.due)} days ago`:daysAway(next.due)===0?'today':daysAway(next.due)===1?'tomorrow':prettyDate(next.due)}. Try a 20-minute focus block, then write down the next step.`}
 if(/break|start|assignment|essay|project/.test(q))return next?`Make the first step small enough to do in 10 minutes. For “${next.title}”, open the instructions, list what you need, and choose one part to begin.`:'Write down the assignment, its due date, and the very first 10-minute step. Add it to your planner so it stays visible.';
 return next?`You have ${open.length} unfinished task${open.length===1?'':'s'}. Your next due is “${next.title}” (${prettyDate(next.due)}). What is one small step you could do in 10 minutes?`:'What is one small step you can finish in 10 minutes? Add coursework and due dates to your planner to help organize your week.'
}
$('#chatForm').onsubmit=e=>{e.preventDefault();const form=e.currentTarget,field=form.elements.message,message=field.value.trim();if(!message)return;addChatBubble(message,'user');field.value='';addChatBubble(localCoachReply(message),'coach');field.focus()};
const voiceStatus=$('#voiceStatus'),voiceButton=$('#voiceInput'),SpeechRecognitionAPI=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null;
if(!SpeechRecognitionAPI){voiceStatus.textContent='Voice input is not available in this browser. You can still type, and read-aloud may work.';voiceButton.title='Speech recognition is not supported in this browser'}
if(!('speechSynthesis'in window)){$('#readAloud').disabled=true;voiceStatus.textContent=SpeechRecognitionAPI?'Speech input is available. Read-aloud is not supported here.':'Voice input and read-aloud are not supported here. You can still type your questions.'}
voiceButton.onclick=()=>{if(!SpeechRecognitionAPI){voiceStatus.classList.add('is-error');return}if(recognition){recognition.stop();return}recognition=new SpeechRecognitionAPI();recognition.lang='en-US';recognition.interimResults=false;recognition.maxAlternatives=1;voiceButton.textContent='Listening…';voiceStatus.textContent='Listening on this device. Speak now.';recognition.onresult=event=>{const field=$('#chatForm').elements.message;field.value=event.results[0][0].transcript;voiceStatus.textContent='Heard you. Sending your question…';$('#chatForm').requestSubmit()};recognition.onerror=event=>{voiceStatus.textContent=event.error==='not-allowed'?'Microphone access was blocked. Allow it in your browser settings or type your question.':`Voice input stopped (${event.error}). You can type your question instead.`;voiceStatus.classList.add('is-error')};recognition.onend=()=>{recognition=null;voiceButton.textContent='🎙 Speak';if(voiceStatus.textContent.startsWith('Listening'))voiceStatus.textContent='No speech captured. Tap Speak to try again.'};recognition.start()};
function exportBackup(){const data={format:'coach-ai-backup',version:1,createdAt:new Date().toISOString(),assignments,activities,sessions,mastery,studyMinutes,name:getLearnerName(),learnerProfile,chatHistory};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='coach-ai-backup.json';a.click();URL.revokeObjectURL(url)}
$('#exportData').onclick=exportBackup;$('#accountButton').onclick=exportBackup;
$('#importData').onclick=()=>$('#backupFile').click();$('#backupFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data.format!=='coach-ai-backup'||!Array.isArray(data.assignments)||!Array.isArray(data.activities))throw new Error('This file is not a Coach AI backup.');assignments=data.assignments;activities=data.activities;sessions=Number(data.sessions)||0;mastery=Number(data.mastery)||0;studyMinutes=Number(data.studyMinutes)||0;chatHistory=Array.isArray(data.chatHistory)?data.chatHistory:[];learnerProfile=data.learnerProfile||{level:'High school',subject:'Math',topic:'',mode:'learn'};localStorage.setItem('coachai.learner',JSON.stringify(learnerProfile));learnerForm.elements.level.value=learnerProfile.level;learnerForm.elements.subject.value=learnerProfile.subject;learnerForm.elements.topic.value=learnerProfile.topic||'';learnerForm.elements.mode.value=learnerProfile.mode;renderLearnerSummary();localStorage.setItem('coachai.name',JSON.stringify(String(data.name||'Student')));localStorage.setItem('coachai.chat',JSON.stringify(chatHistory));saveAssignments();render();setProfile();$('#chatMessages').replaceChildren();chatHistory.forEach(m=>addChatBubble(m.text,m.kind,false));alert('Backup restored on this device.')}catch(err){alert(err.message||'Could not read that backup file.')}finally{e.target.value=''}};
$('#clearData').onclick=()=>{if(!confirm('Clear all Coach AI data saved in this browser? Export a backup first if you want to keep it.'))return;Object.keys(localStorage).filter(k=>k.startsWith('coachai.')).forEach(k=>localStorage.removeItem(k));location.reload()};

// Guided lessons: explanations, worked examples, retrieval practice, and feedback all run locally.
const lessons={
 'linear-equations':{subject:'MATH · FOUNDATIONS',title:'Solve a linear equation',explanation:'An equation is a balance: both sides have the same value. To find the unknown, use inverse operations to undo what was done to it. Whatever you do to one side, do to the other.',example:'Solve 3x + 5 = 20. Subtract 5 from both sides: 3x = 15. Divide both sides by 3: x = 5. Check: 3(5) + 5 = 20.',takeaway:'The goal is to get the variable alone while keeping the equation balanced.',question:'Solve 2x + 7 = 19. What is x?',answers:['5','6','13','26'],correct:1,feedback:'Subtract 7 first: 2x = 12. Then divide by 2, so x = 6. Check by substituting: 2(6) + 7 = 19.',quiz:[{question:'Solve 3x + 4 = 19.',answers:['3','5','7','15'],correct:1,feedback:'Subtract 4, then divide by 3: x = 5.'},{question:'Solve 4x − 8 = 12.',answers:['1','4','5','20'],correct:2,feedback:'Add 8, then divide by 4: x = 5.'}]},
 'fractions':{subject:'MATH · NUMBER SENSE',title:'Add fractions with unlike denominators',explanation:'The denominator tells you the size of the pieces. You can only add fractions once their pieces are the same size. Find a common denominator, rename each fraction, then add the numerators.',example:'Add 1/3 + 1/4. A common denominator is 12. Rename: 1/3 = 4/12 and 1/4 = 3/12. Add: 4/12 + 3/12 = 7/12.',takeaway:'Make equal-sized pieces first. Add the top numbers and keep the shared denominator.',question:'What is 1/2 + 1/3?',answers:['2/5','5/6','1/6','2/6'],correct:1,feedback:'A common denominator is 6: 1/2 = 3/6 and 1/3 = 2/6. Their sum is 5/6.',quiz:[{question:'What is 1/4 + 1/2?',answers:['2/6','3/4','1/6','3/8'],correct:1,feedback:'Rename 1/2 as 2/4, then add: 3/4.'},{question:'What is 2/3 + 1/6?',answers:['3/9','1/2','5/6','3/6'],correct:2,feedback:'Rename 2/3 as 4/6, then add: 5/6.'}]},
 'photosynthesis':{subject:'BIOLOGY · PLANT SCIENCE',title:'How photosynthesis stores energy',explanation:'Plants use light energy captured by chlorophyll to combine carbon dioxide from air with water. This makes glucose, which stores chemical energy, and releases oxygen. Light provides energy; it is not itself a material ingredient in the products.',example:'carbon dioxide + water + light energy → glucose + oxygen. The process happens mainly in chloroplasts in green plant cells.',takeaway:'Photosynthesis moves energy from sunlight into chemical energy stored in glucose.',question:'Which product stores the captured energy for the plant to use?',answers:['Oxygen','Water','Glucose','Carbon dioxide'],correct:2,feedback:'Glucose stores chemical energy that the plant can use for growth and cell processes. Oxygen is released as a by-product.',quiz:[{question:'Which gas do plants take in for photosynthesis?',answers:['Oxygen','Carbon dioxide','Nitrogen','Hydrogen'],correct:1,feedback:'Plants take in carbon dioxide and release oxygen.'},{question:'Where does most photosynthesis happen in a plant cell?',answers:['Nucleus','Mitochondrion','Chloroplast','Cell wall'],correct:2,feedback:'Chloroplasts contain chlorophyll, which captures light.'}]},
 'covalent-bonds':{subject:'CHEMISTRY · BONDING',title:'Why atoms form covalent bonds',explanation:'Atoms form covalent bonds by sharing pairs of electrons. Sharing can help each atom reach a more stable outer electron arrangement. Covalent bonds commonly form between non-metal atoms.',example:'In a water molecule, oxygen shares electron pairs with two hydrogen atoms. The shared electrons attract both nuclei and hold the atoms together.',takeaway:'Covalent means electrons are shared between atoms.',question:'What happens to electrons in a covalent bond?',answers:['They are shared between atoms','They are transferred to a metal','They disappear','They become protons'],correct:0,feedback:'Exactly: covalent bonds involve shared electron pairs. Electron transfer is associated with ionic bonding.',quiz:[{question:'Covalent bonds most often form between which atoms?',answers:['Two non-metals','Two metals','A metal and a non-metal only','Noble gases only'],correct:0,feedback:'Covalent bonding commonly joins non-metals through shared electrons.'},{question:'Why does sharing electrons hold atoms together?',answers:['Shared electrons attract both nuclei','Atoms lose every electron','Nuclei stop having charge','Electrons become neutrons'],correct:0,feedback:'The shared electrons are attracted to both positive nuclei.'}]},
 'thesis-statements':{subject:'ENGLISH · ARGUMENT WRITING',title:'Build a clear thesis statement',explanation:'A thesis is the main claim your writing will support. A strong thesis answers the prompt, takes a position, and gives the reader a reason or a useful map of the argument. It should be specific enough to support with evidence.',example:'Prompt: Should schools start later? Weak: “School start times are important.” Stronger: “Schools should start later because additional sleep can improve students’ attention and wellbeing.”',takeaway:'Make a debatable claim, then preview why you believe it.',question:'Which is the strongest thesis for an essay about school gardens?',answers:['School gardens are green.','This essay is about gardens.','Schools should grow gardens because they give students hands-on science practice and fresh produce.','Many schools have students.'],correct:2,feedback:'This option takes a clear position and gives two reasons the essay can support with evidence.',quiz:[{question:'What should a strong thesis do?',answers:['List the essay title','Make a specific claim that answers the prompt','Repeat the prompt exactly','Avoid taking a position'],correct:1,feedback:'A thesis makes a focused, supportable claim in response to the prompt.'},{question:'Which detail makes a thesis easier to support?',answers:['A clear reason for the claim','A broad topic only','An unrelated fact','A question with no answer'],correct:0,feedback:'A reason gives the essay a clear argument and helps guide evidence.'}]}
};
const lessonSelect=$('#lessonSelect');let activeLesson=null,lessonAnswered=false,quizQuestions=[],quizIndex=0,quizScore=0;
function renderQuizQuestion(){lessonAnswered=false;const q=quizQuestions[quizIndex];$('#lessonQuestion').textContent=q.question;$('#quizProgress').textContent=`Question ${quizIndex+1} of ${quizQuestions.length} · Score ${quizScore}`;$('#lessonAnswers').replaceChildren(...q.answers.map((answer,i)=>{const b=document.createElement('button');b.type='button';b.className='lesson-answer';b.textContent=answer;b.onclick=()=>checkLessonAnswer(i);return b}));$('#lessonFeedback').textContent='';$('#lessonFeedback').className='lesson-feedback';$('#lessonAgain').hidden=true}
function showLesson(){activeLesson=lessons[lessonSelect.value]||lessons['linear-equations'];quizQuestions=[{question:activeLesson.question,answers:activeLesson.answers,correct:activeLesson.correct,feedback:activeLesson.feedback},...(activeLesson.quiz||[])];quizIndex=0;quizScore=0;$('#lessonSubject').textContent=`${activeLesson.subject} · ${learnerProfile.level.toUpperCase()}`;$('#lessonTitle').textContent=activeLesson.title;const scaffold=learnerProfile.level==='Upper primary'?'Let’s break it into small, clear steps. ':learnerProfile.level==='Middle school'?'Track each step and check your thinking as you go. ':learnerProfile.level==='College / adult'?'Focus on the underlying principle and how to apply it. ':'Focus on the method and be ready to explain why each step works. ';$('#lessonExplanation').textContent=scaffold+activeLesson.explanation;$('#lessonExample').textContent=activeLesson.example;$('#lessonTakeaway').textContent=learnerProfile.mode==='test'?`Test focus: ${activeLesson.takeaway} Practise explaining each step without looking at the example.`:activeLesson.takeaway;$('#practiceLabel').textContent=learnerProfile.mode==='quiz'?'QUIZ MODE · NO NOTES':learnerProfile.mode==='test'?'TEST PRACTICE':'YOUR TURN';renderQuizQuestion();$('#lessonEmpty').hidden=true;$('#lessonPractice').hidden=learnerProfile.mode!=='quiz';$('#lessonContent').hidden=learnerProfile.mode==='quiz'}
function checkLessonAnswer(index){if(lessonAnswered)return;lessonAnswered=true;const q=quizQuestions[quizIndex],correct=index===q.correct;if(correct)quizScore++;const buttons=$('#lessonAnswers').querySelectorAll('button');buttons.forEach((b,i)=>{b.disabled=true;if(i===q.correct)b.classList.add('correct');else if(i===index)b.classList.add('incorrect')});$('#lessonFeedback').textContent=(correct?'Correct. ':'Not quite. ')+q.feedback;$('#lessonFeedback').classList.add(correct?'is-correct':'is-review');$('#quizProgress').textContent=`Question ${quizIndex+1} of ${quizQuestions.length} · Score ${quizScore}`;$('#lessonAgain').textContent=quizIndex<quizQuestions.length-1?'Next question':'Try another lesson';$('#lessonAgain').hidden=false;sessions+=1;if(correct)mastery=Math.min(100,mastery+4);persistLearnerState();render()}
$('#beginLesson').onclick=showLesson;lessonSelect.onchange=()=>{if(activeLesson)showLesson()};$('#startLessonPractice').onclick=()=>{$('#lessonContent').hidden=true;$('#lessonPractice').hidden=false};$('#lessonAgain').onclick=()=>{if(quizIndex<quizQuestions.length-1){quizIndex++;renderQuizQuestion();$('#lessonAgain').textContent='Next question'}else{lessonSelect.selectedIndex=(lessonSelect.selectedIndex+1)%lessonSelect.options.length;showLesson()}};
const learnerForm=$('#learnerForm');learnerForm.elements.level.value=learnerProfile.level;learnerForm.elements.subject.value=learnerProfile.subject;learnerForm.elements.topic.value=learnerProfile.topic||'';learnerForm.elements.mode.value=learnerProfile.mode;function renderLearnerSummary(){$('#learnerSummary').textContent=`${learnerProfile.level} · ${learnerProfile.subject}${learnerProfile.topic?` · ${learnerProfile.topic}`:''} · ${learnerProfile.mode==='test'?'Preparing for a test':learnerProfile.mode==='quiz'?'Quiz practice':'Learning a topic'}. Saved only in this browser.`}renderLearnerSummary();learnerForm.onsubmit=e=>{e.preventDefault();const data=new FormData(learnerForm);learnerProfile={level:String(data.get('level')),subject:String(data.get('subject')),topic:String(data.get('topic')).trim(),mode:String(data.get('mode'))};localStorage.setItem('coachai.learner',JSON.stringify(learnerProfile));renderLearnerSummary();const topic=learnerProfile.topic.toLowerCase();const suggested=/fraction/.test(topic)?'fractions':/photo|plant/.test(topic)?'photosynthesis':/bond|electron/.test(topic)?'covalent-bonds':/thesis|essay/.test(topic)?'thesis-statements':/equation|algebra/.test(topic)?'linear-equations':learnerProfile.subject==='Biology'?'photosynthesis':learnerProfile.subject==='Chemistry'?'covalent-bonds':learnerProfile.subject==='English'?'thesis-statements':lessonSelect.value;lessonSelect.value=suggested;$('#learnerSummary').textContent+=` Suggested lesson: ${lessons[suggested].title}.`;if(activeLesson)showLesson()};
function goToLessons(start=false){$('#learn').scrollIntoView({behavior:'smooth',block:'start'});if(start)showLesson()}
$('#startLessonShortcut').onclick=()=>goToLessons(true);$('#nextArrow').onclick=()=>goToLessons(true);
// Profile is a local display name, not an account or email address.
$('#profileButton').onclick=()=>{const current=getLearnerName();const next=prompt('What name should Coach AI use?',current);if(next===null)return;const name=next.trim().slice(0,40)||'Student';localStorage.setItem('coachai.name',JSON.stringify(name));setProfile();$('.welcome h1').innerHTML=`Welcome back, ${escapeHTML(name)}<span class="wave">✳</span>`};
// Quick access to due dates and the planner.
const notificationsDialog=$('#notificationsDialog');$('#notificationsButton').onclick=()=>{const upcoming=assignments.filter(a=>!a.done).sort((a,b)=>a.due.localeCompare(b.due)).slice(0,5);$('#notificationList').innerHTML=upcoming.length?upcoming.map(a=>`<div class="notification-item"><b>${escapeHTML(a.title)}</b><small>${escapeHTML(a.subject||'Personal')} · ${escapeHTML(daysAway(a.due)<0?`${-daysAway(a.due)} days overdue`:daysAway(a.due)===0?'Due today':daysAway(a.due)===1?'Due tomorrow':prettyDate(a.due))}</small></div>`).join(''):'<p class="calendar-empty">No upcoming coursework. Add a due date in your planner to see it here.</p>';notificationsDialog.showModal()};$('#closeNotifications').onclick=()=>notificationsDialog.close();$('#notificationsPlanner').onclick=()=>{notificationsDialog.close();$('#planner').scrollIntoView({behavior:'smooth',block:'start'})};
$('#jumpToday').onclick=()=>{selectedDay=dateKey(new Date());renderWeek();$('#planner').scrollIntoView({behavior:'smooth',block:'start'})};
document.querySelectorAll('.nav-item[href^="#"]').forEach(link=>link.addEventListener('click',()=>{document.querySelectorAll('.nav-item').forEach(item=>item.classList.toggle('active',item===link))}));
